Closes #6
geta-org/sex-adapt-backend pull request #7
Opened 2022-09-30 19:38 UTC by FabioNeves00

# Overview
Creation of Review CRUD module without Establishment connection.
# Usage
## Routes - **ALL OF THEM REQUIRES ACCESS AND REFRESH TOKEN**:
- /review/:id -> GET - get a review and its owner  - -> return review with user relation
- /review/ -> GET - get all reviews and its owers - -> return all reviews with user relation
- /review/:id -> DELETE - deletes a review - -> returns nothing
- /review/ -> POST - creates a review using userId from refresh token, grade and comment - -> returns review with user relation

2022-10-05 01:21 UTC, olucasfreitas requested changes

2022-10-05 01:21 UTC, olucasfreitas commented on src/common/decorators/get-current-user-id.decorator.ts
> +	(_: undefined, context: ExecutionContext): number => {
esse undefined acontece porquê o conteúdo que vem pode ser indefinido mesmo, ou é por alguma outra razão?

2022-10-05 01:21 UTC, olucasfreitas commented on src/common/decorators/get-current-user-id.decorator.ts
> +		console.log(context.switchToHttp().getRequest());
remover console.log

2022-10-05 01:21 UTC, olucasfreitas commented on src/models/review/interfaces/review.interface.ts
> +	// establishmentId: string
remover comentário, ou colocar como TODO caso ainda vá ser feito

2022-10-05 01:21 UTC, olucasfreitas commented on src/models/user/dto/create-user.dto.ts
> +		message: 'password is too weak'
se esse erro vai para o front, deveria ser em português ?

2022-10-05 03:50 UTC, FabioNeves00 commented on src/common/decorators/get-current-user-id.decorator.ts
> +	(_: undefined, context: ExecutionContext): number => {
esse primeiro só n vai ser enviado em nenhuma situação que o decorator for usado, sempre vai vir undefined msm

2022-10-05 03:51 UTC, FabioNeves00 commented on src/models/review/review.service.ts
> +				user: userId as any,
eu tbm n entendi pra te ser sincero, o tipo do id eh string mas tava dando um erro aleatorio do typescript

2022-10-05 03:52 UTC, FabioNeves00 commented on src/models/user/dto/create-user.dto.ts
> +		message: 'password is too weak'
por padrao esses decorators retornam td em ingles, se no front quiser q seja facilitado a mensagem de erro e pegar a resposta direta do back e colocar la, posso personalizar todos pra portugues

2022-10-07 12:34 UTC, FabioNeves00 commented
Tudo certo linda ! @olucasfreitas

2022-10-13 18:50 UTC, merged